/**
 * Gemini Subtopic Extraction Service
 * Uses Google's Gemini API to intelligently extract chapters, headings, and subtopics
 * More accurate than pattern matching alone
 */

const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize Gemini API
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * Use Gemini to extract document structure
 * @param {string} text - Full extracted text from document
 * @param {string} fileName - Original filename for context
 * @returns {Promise<Array>} Array of extracted subtopics with structure
 */
const extractStructureWithGemini = async (text) => {
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured in .env');
    }

    console.log('🤖 Analyzing text with Gemini API...');

    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

    // Create a detailed prompt for structure extraction
    // FOCUS: Extract only Unit-based subtopics, ignore Course Outcomes, References, TextBooks, Practicals
    const prompt = `You are an expert document analyzer specialized in extracting course syllabus structure.

CRITICAL INSTRUCTIONS - FOLLOW EXACTLY:
1. Extract ONLY the learning units/modules (Unit I, Unit II, Unit III, Unit IV, Unit V, Unit VI, etc.)
2. DO NOT include anything that is NOT a unit
3. COMPLETELY IGNORE these sections - NEVER include them:
   - Course Outcomes
   - Course Credit
   - Learning Objectives  
   - References
   - Text Books
   - Textbooks
   - Practicals
   - Experiments
   - Course Title/Header
   - Any metadata or non-unit information
4. For each unit, extract the unit title and main topics covered
5. Preserve the original order of units

TEXT TO ANALYZE:
${text}

RESPOND ONLY with a valid JSON array containing ONLY units. Example format:
[
  {
    "level": 1,
    "title": "Unit I: Introduction to DevOps",
    "description": "Basics and fundamentals of DevOps",
    "content": "Content of Unit I here",
    "order": 0
  },
  {
    "level": 1,
    "title": "Unit II: Linux Commands",
    "description": "Essential Linux commands",
    "content": "Content of Unit II here",
    "order": 1
  }
]

STRICT RULES:
- MUST start with "Unit" in the title
- No course metadata
- No references or textbooks
- No outcomes or objectives
- No practicals section
- Only units matter
- Return empty array [] if no units found
- Return ONLY valid JSON`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    // Parse JSON response
    let extractedStructure;
    try {
      extractedStructure = JSON.parse(responseText);
    } catch (parseError) {
      // Try to extract JSON from response if wrapped in markdown
      const jsonMatch = responseText.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        extractedStructure = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('Failed to parse Gemini response as JSON');
      }
    }

    console.log(`✅ Gemini extracted ${extractedStructure.length} items (before filtering)`);

    // Convert Gemini response to subtopic format
    // Only include items that are actual units
    const subtopics = extractedStructure
      .filter((item) => {
        const title = (item.title || '').toLowerCase();
        // Only keep items that contain "unit" in the title
        const isUnit = title.includes('unit');
        if (!isUnit) {
          console.log(`⏭️  Filtering out non-unit: "${item.title}"`);
        }
        return isUnit;
      })
      .map((item, index) => ({
        order: index,
        title: item.title || 'Untitled',
        description: item.description || '',
        extractedText: item.content || '',
        detectionMethod: 'gemini-ai',
        confidence: 0.92, // High confidence for AI extraction
        hierarchyLevel: item.level || 1,
      }));

    console.log(`✅ After filtering: ${subtopics.length} units found`);

    return subtopics;
  } catch (error) {
    console.error('❌ Gemini extraction error:', error.message);
    throw new Error(`Failed to extract structure with Gemini: ${error.message}`);
  }
};

/**
 * Generate detailed notes for a specific subtopic using Gemini
 * @param {string} subtopicTitle - Title of the subtopic
 * @param {string} subtopicContent - Content of the subtopic
 * @returns {Promise<string>} Detailed notes generated by Gemini
 */
const generateDetailedNotes = async (subtopicTitle, subtopicContent) => {
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    console.log(`📝 Generating detailed notes for: "${subtopicTitle}"`);

    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

    const prompt = `Create comprehensive study notes for the following topic based on the provided content.

TOPIC: ${subtopicTitle}

CONTENT:
${subtopicContent}

Generate detailed study notes that include:
1. **Key Concepts**: Main ideas and definitions
2. **Detailed Explanation**: Comprehensive coverage of the topic
3. **Examples**: Real-world or practical examples
4. **Important Points**: Highlights and takeaways
5. **Summary**: Brief recap of the entire topic

Format the response in markdown with clear sections and bullet points for easy reading.`;

    const result = await model.generateContent(prompt);
    const notes = result.response.text();

    console.log(`✅ Generated ${notes.length} characters of detailed notes`);
    return notes;
  } catch (error) {
    console.error('❌ Note generation error:', error.message);
    throw new Error(`Failed to generate notes: ${error.message}`);
  }
};

/**
 * Summarize a subtopic using Gemini
 * @param {string} subtopicTitle - Title of the subtopic
 * @param {string} subtopicContent - Content of the subtopic
 * @returns {Promise<string>} Brief summary of the subtopic
 */
const generateSummary = async (subtopicTitle, subtopicContent) => {
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    console.log(`📄 Generating summary for: "${subtopicTitle}"`);

    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

    const prompt = `Create a concise 2-3 sentence summary of the following topic:

TOPIC: ${subtopicTitle}

CONTENT:
${subtopicContent}

Provide only the summary, no extra text.`;

    const result = await model.generateContent(prompt);
    const summary = result.response.text();

    console.log(`✅ Generated summary (${summary.length} characters)`);
    return summary;
  } catch (error) {
    console.error('❌ Summary generation error:', error.message);
    throw new Error(`Failed to generate summary: ${error.message}`);
  }
};

/**
 * Generate comprehensive study notes for a subtopic
 * @param {string} subtopicTitle - Title of the subtopic
 * @param {string} subtopicDescription - Description/content of the subtopic
 * @returns {Promise<Object>} Generated notes with sections and key concepts
 */
const generateComprehensiveNotes = async (subtopicTitle, subtopicDescription) => {
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    console.log(`📚 Generating comprehensive notes for: "${subtopicTitle}"`);

    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

    const prompt = `You are an expert educational content creator. Generate comprehensive study notes for the following topic.

TOPIC: ${subtopicTitle}

DESCRIPTION: ${subtopicDescription}

Please provide detailed study notes in the following JSON format ONLY (no additional text):
{
  "title": "${subtopicTitle}",
  "keyPoints": ["point1", "point2", "point3", ...],
  "mainSections": [
    {
      "heading": "Section Title",
      "content": "Detailed explanation of this section",
      "concepts": ["concept1", "concept2"]
    }
  ],
  "importantTerms": [
    {
      "term": "terminology",
      "definition": "clear definition"
    }
  ],
  "practicalApplications": ["application1", "application2"],
  "learningOutcomes": ["outcome1", "outcome2"],
  "summary": "Brief summary of the entire topic"
}

Generate ONLY the JSON object, no markdown, no explanations.`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text().trim();
    
    // Parse JSON response
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Gemini response was not valid JSON');
    }
    
    const notes = JSON.parse(jsonMatch[0]);
    console.log(`✅ Generated comprehensive notes (${responseText.length} characters)`);
    
    return {
      success: true,
      notes: notes,
      generatedAt: new Date(),
      contentLength: responseText.length
    };
  } catch (error) {
    console.error('❌ Notes generation error:', error.message);
    throw new Error(`Failed to generate notes: ${error.message}`);
  }
};

/**
 * Convert JSON notes to Markdown format for frontend display
 * @param {Object} jsonNotes - Notes in JSON format
 * @returns {string} Markdown formatted notes
 */
const convertNotesToMarkdown = (jsonNotes) => {
  let markdown = '';

  // Title
  markdown += `# ${jsonNotes.title}\n\n`;

  // Key Points
  if (jsonNotes.keyPoints && jsonNotes.keyPoints.length > 0) {
    markdown += `## Key Points\n\n`;
    jsonNotes.keyPoints.forEach((point) => {
      markdown += `- ${point}\n`;
    });
    markdown += '\n';
  }

  // Main Sections
  if (jsonNotes.mainSections && jsonNotes.mainSections.length > 0) {
    markdown += `## Main Sections\n\n`;
    jsonNotes.mainSections.forEach((section) => {
      markdown += `### ${section.heading}\n\n`;
      markdown += `${section.content}\n\n`;
      if (section.concepts && section.concepts.length > 0) {
        markdown += `**Concepts:** ${section.concepts.join(', ')}\n\n`;
      }
    });
  }

  // Important Terms
  if (jsonNotes.importantTerms && jsonNotes.importantTerms.length > 0) {
    markdown += `## Important Terms\n\n`;
    jsonNotes.importantTerms.forEach((term) => {
      markdown += `**${term.term}:** ${term.definition}\n\n`;
    });
  }

  // Practical Applications
  if (jsonNotes.practicalApplications && jsonNotes.practicalApplications.length > 0) {
    markdown += `## Practical Applications\n\n`;
    jsonNotes.practicalApplications.forEach((app) => {
      markdown += `- ${app}\n`;
    });
    markdown += '\n';
  }

  // Learning Outcomes
  if (jsonNotes.learningOutcomes && jsonNotes.learningOutcomes.length > 0) {
    markdown += `## Learning Outcomes\n\n`;
    jsonNotes.learningOutcomes.forEach((outcome) => {
      markdown += `- ${outcome}\n`;
    });
    markdown += '\n';
  }

  // Summary
  if (jsonNotes.summary) {
    markdown += `## Summary\n\n`;
    markdown += `${jsonNotes.summary}\n`;
  }

  return markdown;
};

module.exports = {
  extractStructureWithGemini,
  generateDetailedNotes,
  generateSummary,
  generateComprehensiveNotes,
  convertNotesToMarkdown,
};
